site_name: Kookaburra
site_url: https://azproductions.github.io/Kookaburra/
#site_author: Name
site_description: >-
  Kookaburra is a simple programming language. With Kookaburra you can choose between the powerful CLI (command-line-interface), or start scripting with its intuitive syntax. The syntax is simple and efficient. Create apps/games and more that are fine-tuned to perfection. Kookaburra is completely free to use, with local files and no data collection. Our aim is to power creativity and inspire young developers. That's why we care about privacy and safety. We love hearing feedback to improve Kookaburra.

nav:
  - Home: index.md
  - Getting started: tutorials/getting started.md
  - Downloads: https://github.com/AZProductions/Kookaburra/releases/
  - Blogs:
    - Publishing Kookaburra into an exe file: blogs/Publishing Kookaburra into an exe file.md
    - Kookaburra linking template: blogs/Kookaburra linking template.md
    - Improving Kookaburra's performance: blogs/Improving Kookaburra's performance.md
    - Kookaburra on the Microsoft Store: blogs/Kookaburra on the Microsoft Store.md
    - The new releasing strategy: blogs/Kookaburra releasing strategy.md
  - Resources:
    - Error list: resources/error-list.md
    - Shortcuts: resources/shortcuts.md


theme:
  logo: assets\favicon.png
  icon:
    repo: fontawesome/brands/github-square
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.indexes
      - navigation.top
      - toc.integrate
      - content.tabs.link
  font:
    text: Roboto
  favicon: assets\favicon50.png
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: dark blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  name: material

repo_name: AZProductions/Kookaburra
repo_url: https://github.com/AZProductions/Kookaburra
edit_uri: ""

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AZProductions/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AZProductions