name: Example workflow for dotNET using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
          json: true
      - uses: garethr/snyk-to-sarif@master
      - uses: actions/upload-artifact@v2
        with:
          name: SARIF
          path: snyk.sarif
      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
