// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GetDownloadVersion;
//
//    var newestVersion = NewestVersion.FromJson(jsonString);

namespace GetDownloadVersion
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class NewestVersion
    {
        [JsonProperty("url_win64")]
        public object UrlWin64 { get; set; }

        [JsonProperty("url_win86")]
        public object UrlWin86 { get; set; }

        [JsonProperty("url_winarm")]
        public object UrlWinarm { get; set; }

        [JsonProperty("url_linux")]
        public object UrlLinux { get; set; }

        [JsonProperty("url_linuxarm")]
        public object UrlLinuxarm { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("date")]
        public string Date { get; set; }
    }

    public partial class NewestVersion
    {
        public static NewestVersion[] FromJson(string json)
        {
            return JsonConvert.DeserializeObject<NewestVersion[]>(json, GetDownloadVersion.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this NewestVersion[] self)
        {
            return JsonConvert.SerializeObject(self, GetDownloadVersion.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
